version: "3.8"

services:
  backend:
    build:
      context: ./backend  # Assuming the backend Dockerfile is in the "backend" directory
    environment:
      # - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/viddychat
    ports:
      - "5005:5005"
    depends_on:
      - postgres
    networks:
      - chatnetwork

  frontend:
    build:
      context: ./frontend  # Assuming the frontend Dockerfile is in the "frontend" directory
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - chatnetwork

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=viddychat
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - chatnetwork

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx/ssl/server.cert:/etc/ssl/certs/server.cert
      - ./nginx/ssl/server.key:/etc/ssl/private/server.key
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - frontend
    environment:
      - NGINX_HOST=localhost
    networks:
      - chatnetwork

volumes:
  postgres_data:

networks:
  chatnetwork: